// <auto-generated />
using LaykaSommelier.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaykaSommelier.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513192228_AddEmployeeEmail")]
    partial class AddEmployeeEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaykaSommelier.Api.Models.Cocktail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cocktail_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Abv")
                        .HasColumnType("double precision")
                        .HasColumnName("cocktail_abv");

                    b.Property<double>("Acidity")
                        .HasColumnType("double precision")
                        .HasColumnName("cocktail_acidity");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cocktail_author");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cocktail_description");

                    b.Property<string>("Glass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cocktail_glass");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cocktail_image_url");

                    b.Property<long>("MakingMethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("cocktail_making_method_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cocktail_name");

                    b.Property<string>("Serving")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cocktail_serving");

                    b.Property<double>("SugarLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("cocktail_sugar_level");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("cocktail_volume");

                    b.HasKey("Id");

                    b.HasIndex("MakingMethodId");

                    b.ToTable("cocktails");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.CocktailIngredient", b =>
                {
                    b.Property<long>("CocktailId")
                        .HasColumnType("bigint")
                        .HasColumnName("cocktail_id");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingredient_id");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("ingredient_volume");

                    b.HasKey("CocktailId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("cocktails_ingredients");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Descriptor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("descriptor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("descriptor_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descriptor_name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("descriptors");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.DescriptorCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("descriptor_category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descriptor_category_color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descriptor_category_name");

                    b.HasKey("Id");

                    b.ToTable("descriptor_categories");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.DescriptorReview", b =>
                {
                    b.Property<long>("DescriptorId")
                        .HasColumnType("bigint")
                        .HasColumnName("descriptor_id");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.HasKey("DescriptorId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("descriptors_reviews");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Drink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("drink_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Abv")
                        .HasColumnType("double precision")
                        .HasColumnName("drink_abv");

                    b.Property<int>("Aged")
                        .HasColumnType("integer")
                        .HasColumnName("drink_aged");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("drink_country");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drink_image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drink_name");

                    b.Property<string>("Producer")
                        .HasColumnType("text")
                        .HasColumnName("drink_producer");

                    b.Property<string>("SubType")
                        .HasColumnType("text")
                        .HasColumnName("drink_sub_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drink_type");

                    b.HasKey("Id");

                    b.ToTable("drinks");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_password");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_position");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ingredient_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Abv")
                        .HasColumnType("double precision")
                        .HasColumnName("ingredient_abv");

                    b.Property<double>("Acidity")
                        .HasColumnType("double precision")
                        .HasColumnName("ingredient_acidity");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredient_image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredient_name");

                    b.Property<double>("SugarLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("ingredient_sugar_level");

                    b.HasKey("Id");

                    b.ToTable("ingredients");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.IngredientDescriptor", b =>
                {
                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingredient_id");

                    b.Property<long>("DescriptorId")
                        .HasColumnType("bigint")
                        .HasColumnName("descriptor_id");

                    b.HasKey("IngredientId", "DescriptorId");

                    b.HasIndex("DescriptorId");

                    b.ToTable("ingredients_descriptors");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.MakingMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("making_method_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Dilution")
                        .HasColumnType("double precision")
                        .HasColumnName("making_method_dilution");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("making_method_name");

                    b.HasKey("Id");

                    b.ToTable("making_methods");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ReviewedDrinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_drink_id");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_source_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("review_url");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedDrinkId");

                    b.HasIndex("SourceId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Source", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id");

                    b.ToTable("sources");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Suggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("suggestion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CocktailId")
                        .HasColumnType("bigint")
                        .HasColumnName("suggested_cocktail_id");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("suggestion_employee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suggestion_status");

                    b.HasKey("Id");

                    b.HasIndex("CocktailId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("suggestions");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Cocktail", b =>
                {
                    b.HasOne("LaykaSommelier.Api.Models.MakingMethod", "MakingMethod")
                        .WithMany()
                        .HasForeignKey("MakingMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MakingMethod");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.CocktailIngredient", b =>
                {
                    b.HasOne("LaykaSommelier.Api.Models.Cocktail", "Cocktail")
                        .WithMany()
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaykaSommelier.Api.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Descriptor", b =>
                {
                    b.HasOne("LaykaSommelier.Api.Models.DescriptorCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.DescriptorReview", b =>
                {
                    b.HasOne("LaykaSommelier.Api.Models.Descriptor", "Descriptor")
                        .WithMany()
                        .HasForeignKey("DescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaykaSommelier.Api.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descriptor");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.IngredientDescriptor", b =>
                {
                    b.HasOne("LaykaSommelier.Api.Models.Descriptor", "Descriptor")
                        .WithMany()
                        .HasForeignKey("DescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaykaSommelier.Api.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descriptor");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Review", b =>
                {
                    b.HasOne("LaykaSommelier.Api.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("ReviewedDrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaykaSommelier.Api.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LaykaSommelier.Api.Models.Suggestion", b =>
                {
                    b.HasOne("LaykaSommelier.Api.Models.Cocktail", "Cocktail")
                        .WithMany()
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaykaSommelier.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
